### ISSUE TITLE
Parser test failing

### ISSUE THREAD

**Issue by arjunsol** [samtingleff/jchronic#4]
Running: mvn test

On:  0.2.7-SNAPSHOT

<pre><code>Failed tests:   test_parse_guess_o_r_g_r(com.mdimension.jchronic.ParserTest): expected:Fri Mar 16 12:30:00 GMT 2007 but was:Fri Mar 16 11:30:00 GMT 2007</code></pre>

<pre><code>-------------------------------------------------------------------------------
Test set: com.mdimension.jchronic.ParserTest
-------------------------------------------------------------------------------
Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.118 sec
test_parse_guess_o_r_g_r(com.mdimension.jchronic.ParserTest)  Time elapsed: 0.006 sec  
junit.framework.AssertionFailedError: expected:Fri Mar 16 12:30:00 GMT 2007 but was:Fri Mar 16 11:30:00 GMT 2007
    at junit.framework.Assert.fail(Assert.java:47)
    at junit.framework.Assert.failNotEquals(Assert.java:283)
    at junit.framework.Assert.assertEquals(Assert.java:64)
    at junit.framework.Assert.assertEquals(Assert.java:71)
    at com.mdimension.jchronic.ParserTest.assertEquals(ParserTest.java:26)
    at com.mdimension.jchronic.ParserTest.assertEquals(ParserTest.java:22)
    at com.mdimension.jchronic.ParserTest.test_parse_guess_o_r_g_r(ParserTest.java:598)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at junit.framework.TestCase.runTest(TestCase.java:168)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)</code></pre>

**Comment by ewanmellor** [comment]
This is happening because the test is parsing a month expression.  This results in a range from midnight March 1 2007 to midnight April 1 2007, and then finding the exact middle of that range.  In some timezones there was a daylight savings time change that month, so the range isn't precisely 24 hours x 31 days long, it's an hour off.  This means that the midpoint of the range is at 12:30 pm on March 16 2017.  The test is written assuming a timezone like that.  If you run the test on a machine where that assumption is bogus (e.g. on a server in UTC that is not doing any daylight savings adjustments) then the test fails.

The whole idea of representing a month-long range by its precise midpoint is pretty dubious anyway.  The test would probably be better if it disabled the "guess" option and checked the beginning and end of the resulting Span instead.

(Do I win a prize, for necroing a five-and-a-half year old issue?)

**Comment by samtingleff** [comment]
just tell me where to send the prize!

**Comment by samtingleff** [comment]
@arjunsol hopefully this fixes your issue. only five-and-a-half years later.
